# Generated by Django 5.1.4 on 2024-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
